ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
        host: localhost

postgres:
  url: "jdbc:postgresql://localhost:5432/rosafiesta"
  user: $PG_USER
  password: $PG_PASSWORD

jwt:
  issuer: "http://localhost"
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "my realm"
  secret: $JWT_SECRET