services:
  db:
    image: postgres:16.3
    container_name: postgres-db-rf
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: rosafiesta
    ports:
      - "5432:5432"

  redis:
    container_name: redis_rf
    restart: unless-stopped
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning