ALTER TABLE IF EXISTS products
    ADD COLUMN IF NOT EXISTS created_by TIMESTAMP WITH TIME ZONE;
ALTER TABLE IF EXISTS products
    ADD COLUMN IF NOT EXISTS updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS products
    ADD COLUMN IF NOT EXISTS updated_by TIMESTAMP WITH TIME ZONE;
ALTER TABLE IF EXISTS products
    ADD COLUMN IF NOT EXISTS deleted TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS products
    ADD COLUMN IF NOT EXISTS deleted_by TIMESTAMP WITH TIME ZONE;