CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE if NOT EXISTS posts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    content VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    user_id UUID NOT NULL,
    created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW()
)