ALTER TABLE IF EXISTS products
    ADD COLUMN IF NOT EXISTS created_by VARCHAR(36) NOT NULL;
ALTER TABLE IF EXISTS products
    ADD COLUMN IF NOT EXISTS updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS products
    ADD COLUMN IF NOT EXISTS updated_by VARCHAR(36);
ALTER TABLE IF EXISTS products
    ADD COLUMN IF NOT EXISTS deleted TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS products
    ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(36);