// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/interfaces.go -destination=internal/services/mocks/interfaces.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dtos "Backend/internal/dtos"
	models "Backend/internal/store/models"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthServicer is a mock of AuthServicer interface.
type MockAuthServicer struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServicerMockRecorder
	isgomock struct{}
}

// MockAuthServicerMockRecorder is the mock recorder for MockAuthServicer.
type MockAuthServicerMockRecorder struct {
	mock *MockAuthServicer
}

// NewMockAuthServicer creates a new mock instance.
func NewMockAuthServicer(ctrl *gomock.Controller) *MockAuthServicer {
	mock := &MockAuthServicer{ctrl: ctrl}
	mock.recorder = &MockAuthServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServicer) EXPECT() *MockAuthServicerMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthServicer) Login(ctx context.Context, email, password string) (*models.UserToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(*models.UserToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthServicerMockRecorder) Login(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthServicer)(nil).Login), ctx, email, password)
}

// RefreshToken mocks base method.
func (m *MockAuthServicer) RefreshToken(ctx context.Context, token string) (*models.UserToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, token)
	ret0, _ := ret[0].(*models.UserToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockAuthServicerMockRecorder) RefreshToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockAuthServicer)(nil).RefreshToken), ctx, token)
}

// RegisterUser mocks base method.
func (m *MockAuthServicer) RegisterUser(ctx context.Context, payload dtos.RegisterUserPayload) (*models.UserWithToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", ctx, payload)
	ret0, _ := ret[0].(*models.UserWithToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockAuthServicerMockRecorder) RegisterUser(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockAuthServicer)(nil).RegisterUser), ctx, payload)
}

// MockUserServicer is a mock of UserServicer interface.
type MockUserServicer struct {
	ctrl     *gomock.Controller
	recorder *MockUserServicerMockRecorder
	isgomock struct{}
}

// MockUserServicerMockRecorder is the mock recorder for MockUserServicer.
type MockUserServicerMockRecorder struct {
	mock *MockUserServicer
}

// NewMockUserServicer creates a new mock instance.
func NewMockUserServicer(ctrl *gomock.Controller) *MockUserServicer {
	mock := &MockUserServicer{ctrl: ctrl}
	mock.recorder = &MockUserServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServicer) EXPECT() *MockUserServicerMockRecorder {
	return m.recorder
}

// ActivateUser mocks base method.
func (m *MockUserServicer) ActivateUser(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateUser", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateUser indicates an expected call of ActivateUser.
func (mr *MockUserServicerMockRecorder) ActivateUser(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateUser", reflect.TypeOf((*MockUserServicer)(nil).ActivateUser), ctx, token)
}

// GetUser mocks base method.
func (m *MockUserServicer) GetUser(ctx context.Context, userID string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, userID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserServicerMockRecorder) GetUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserServicer)(nil).GetUser), ctx, userID)
}

// MockPostServicer is a mock of PostServicer interface.
type MockPostServicer struct {
	ctrl     *gomock.Controller
	recorder *MockPostServicerMockRecorder
	isgomock struct{}
}

// MockPostServicerMockRecorder is the mock recorder for MockPostServicer.
type MockPostServicerMockRecorder struct {
	mock *MockPostServicer
}

// NewMockPostServicer creates a new mock instance.
func NewMockPostServicer(ctrl *gomock.Controller) *MockPostServicer {
	mock := &MockPostServicer{ctrl: ctrl}
	mock.recorder = &MockPostServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostServicer) EXPECT() *MockPostServicerMockRecorder {
	return m.recorder
}

// CreateComment mocks base method.
func (m *MockPostServicer) CreateComment(ctx context.Context, comment *models.Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", ctx, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockPostServicerMockRecorder) CreateComment(ctx, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockPostServicer)(nil).CreateComment), ctx, comment)
}

// CreatePost mocks base method.
func (m *MockPostServicer) CreatePost(ctx context.Context, post *models.Post) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", ctx, post)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockPostServicerMockRecorder) CreatePost(ctx, post any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockPostServicer)(nil).CreatePost), ctx, post)
}

// DeletePost mocks base method.
func (m *MockPostServicer) DeletePost(ctx context.Context, postID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePost", ctx, postID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePost indicates an expected call of DeletePost.
func (mr *MockPostServicerMockRecorder) DeletePost(ctx, postID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePost", reflect.TypeOf((*MockPostServicer)(nil).DeletePost), ctx, postID)
}

// GetComments mocks base method.
func (m *MockPostServicer) GetComments(ctx context.Context, postID string) ([]models.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComments", ctx, postID)
	ret0, _ := ret[0].([]models.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComments indicates an expected call of GetComments.
func (mr *MockPostServicerMockRecorder) GetComments(ctx, postID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComments", reflect.TypeOf((*MockPostServicer)(nil).GetComments), ctx, postID)
}

// GetPost mocks base method.
func (m *MockPostServicer) GetPost(ctx context.Context, postID string) (*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPost", ctx, postID)
	ret0, _ := ret[0].(*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPost indicates an expected call of GetPost.
func (mr *MockPostServicerMockRecorder) GetPost(ctx, postID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPost", reflect.TypeOf((*MockPostServicer)(nil).GetPost), ctx, postID)
}

// UpdatePost mocks base method.
func (m *MockPostServicer) UpdatePost(ctx context.Context, post *models.Post) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePost", ctx, post)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePost indicates an expected call of UpdatePost.
func (mr *MockPostServicerMockRecorder) UpdatePost(ctx, post any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePost", reflect.TypeOf((*MockPostServicer)(nil).UpdatePost), ctx, post)
}

// MockArticleServicer is a mock of ArticleServicer interface.
type MockArticleServicer struct {
	ctrl     *gomock.Controller
	recorder *MockArticleServicerMockRecorder
	isgomock struct{}
}

// MockArticleServicerMockRecorder is the mock recorder for MockArticleServicer.
type MockArticleServicerMockRecorder struct {
	mock *MockArticleServicer
}

// NewMockArticleServicer creates a new mock instance.
func NewMockArticleServicer(ctrl *gomock.Controller) *MockArticleServicer {
	mock := &MockArticleServicer{ctrl: ctrl}
	mock.recorder = &MockArticleServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleServicer) EXPECT() *MockArticleServicerMockRecorder {
	return m.recorder
}

// CreateArticle mocks base method.
func (m *MockArticleServicer) CreateArticle(ctx context.Context, article *models.Article) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArticle", ctx, article)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateArticle indicates an expected call of CreateArticle.
func (mr *MockArticleServicerMockRecorder) CreateArticle(ctx, article any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArticle", reflect.TypeOf((*MockArticleServicer)(nil).CreateArticle), ctx, article)
}

// DeleteArticle mocks base method.
func (m *MockArticleServicer) DeleteArticle(ctx context.Context, articleID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArticle", ctx, articleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteArticle indicates an expected call of DeleteArticle.
func (mr *MockArticleServicerMockRecorder) DeleteArticle(ctx, articleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArticle", reflect.TypeOf((*MockArticleServicer)(nil).DeleteArticle), ctx, articleID)
}

// GetAllArticles mocks base method.
func (m *MockArticleServicer) GetAllArticles(ctx context.Context) ([]models.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllArticles", ctx)
	ret0, _ := ret[0].([]models.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllArticles indicates an expected call of GetAllArticles.
func (mr *MockArticleServicerMockRecorder) GetAllArticles(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllArticles", reflect.TypeOf((*MockArticleServicer)(nil).GetAllArticles), ctx)
}

// GetArticle mocks base method.
func (m *MockArticleServicer) GetArticle(ctx context.Context, articleID string) (*models.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticle", ctx, articleID)
	ret0, _ := ret[0].(*models.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticle indicates an expected call of GetArticle.
func (mr *MockArticleServicerMockRecorder) GetArticle(ctx, articleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticle", reflect.TypeOf((*MockArticleServicer)(nil).GetArticle), ctx, articleID)
}

// UpdateArticle mocks base method.
func (m *MockArticleServicer) UpdateArticle(ctx context.Context, article *models.Article) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateArticle", ctx, article)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateArticle indicates an expected call of UpdateArticle.
func (mr *MockArticleServicerMockRecorder) UpdateArticle(ctx, article any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateArticle", reflect.TypeOf((*MockArticleServicer)(nil).UpdateArticle), ctx, article)
}

// MockCategoryServicer is a mock of CategoryServicer interface.
type MockCategoryServicer struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryServicerMockRecorder
	isgomock struct{}
}

// MockCategoryServicerMockRecorder is the mock recorder for MockCategoryServicer.
type MockCategoryServicerMockRecorder struct {
	mock *MockCategoryServicer
}

// NewMockCategoryServicer creates a new mock instance.
func NewMockCategoryServicer(ctrl *gomock.Controller) *MockCategoryServicer {
	mock := &MockCategoryServicer{ctrl: ctrl}
	mock.recorder = &MockCategoryServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryServicer) EXPECT() *MockCategoryServicerMockRecorder {
	return m.recorder
}

// CreateCategory mocks base method.
func (m *MockCategoryServicer) CreateCategory(ctx context.Context, category *models.Category) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", ctx, category)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockCategoryServicerMockRecorder) CreateCategory(ctx, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockCategoryServicer)(nil).CreateCategory), ctx, category)
}

// DeleteCategory mocks base method.
func (m *MockCategoryServicer) DeleteCategory(ctx context.Context, categoryID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", ctx, categoryID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory.
func (mr *MockCategoryServicerMockRecorder) DeleteCategory(ctx, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockCategoryServicer)(nil).DeleteCategory), ctx, categoryID)
}

// GetAllCategories mocks base method.
func (m *MockCategoryServicer) GetAllCategories(ctx context.Context) ([]models.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCategories", ctx)
	ret0, _ := ret[0].([]models.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCategories indicates an expected call of GetAllCategories.
func (mr *MockCategoryServicerMockRecorder) GetAllCategories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCategories", reflect.TypeOf((*MockCategoryServicer)(nil).GetAllCategories), ctx)
}

// GetArticlesByCategory mocks base method.
func (m *MockCategoryServicer) GetArticlesByCategory(ctx context.Context, categoryID string) ([]models.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticlesByCategory", ctx, categoryID)
	ret0, _ := ret[0].([]models.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticlesByCategory indicates an expected call of GetArticlesByCategory.
func (mr *MockCategoryServicerMockRecorder) GetArticlesByCategory(ctx, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticlesByCategory", reflect.TypeOf((*MockCategoryServicer)(nil).GetArticlesByCategory), ctx, categoryID)
}

// GetCategory mocks base method.
func (m *MockCategoryServicer) GetCategory(ctx context.Context, categoryID string) (*models.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategory", ctx, categoryID)
	ret0, _ := ret[0].(*models.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategory indicates an expected call of GetCategory.
func (mr *MockCategoryServicerMockRecorder) GetCategory(ctx, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategory", reflect.TypeOf((*MockCategoryServicer)(nil).GetCategory), ctx, categoryID)
}

// UpdateCategory mocks base method.
func (m *MockCategoryServicer) UpdateCategory(ctx context.Context, category *models.Category) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", ctx, category)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockCategoryServicerMockRecorder) UpdateCategory(ctx, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockCategoryServicer)(nil).UpdateCategory), ctx, category)
}

// MockFeedServicer is a mock of FeedServicer interface.
type MockFeedServicer struct {
	ctrl     *gomock.Controller
	recorder *MockFeedServicerMockRecorder
	isgomock struct{}
}

// MockFeedServicerMockRecorder is the mock recorder for MockFeedServicer.
type MockFeedServicerMockRecorder struct {
	mock *MockFeedServicer
}

// NewMockFeedServicer creates a new mock instance.
func NewMockFeedServicer(ctrl *gomock.Controller) *MockFeedServicer {
	mock := &MockFeedServicer{ctrl: ctrl}
	mock.recorder = &MockFeedServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedServicer) EXPECT() *MockFeedServicerMockRecorder {
	return m.recorder
}

// GetUserFeed mocks base method.
func (m *MockFeedServicer) GetUserFeed(ctx context.Context, userID string, p models.PaginatedFeedQueryModel) ([]models.PostWithMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserFeed", ctx, userID, p)
	ret0, _ := ret[0].([]models.PostWithMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserFeed indicates an expected call of GetUserFeed.
func (mr *MockFeedServicerMockRecorder) GetUserFeed(ctx, userID, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserFeed", reflect.TypeOf((*MockFeedServicer)(nil).GetUserFeed), ctx, userID, p)
}
